### ISSUE TITLE
🐛 dot-jp and dot-sg is not working.

### ISSUE THREAD

**Issue by daemonserj** [zoonderkins/blahdns#294]
dot-jp and dot-sg are not working completely.
dot-de and dot-ch work as Private DNS in Android but not respond or respond SERVFAIL through stubby.

**Comment by LucioAmely** [comment]
Up, I can confirm it has been like this for 3 days.

**Comment by LucioAmely** [comment]
@zoonderkins Sorry for the ping, I'm pinging you because this issue is urgent.

**Comment by zoonderkins** [comment]
Hi @LucioAmely 

Problem has been solved, please try again. 
Sorry for the delay, I'm been busy this few months.

**Comment by LucioAmely** [comment]
Switzerland Server is still not working. It's giving the following error on DnsCrypt:

Incorrect signature for provider name: [2.dnscrypt-cert.blahdns.com.]

Also not working through DoT as well.

**Comment by zoonderkins** [comment]
<img width="779" alt="Screenshot 2024-01-23 at 01 50 12" src="https://github.com/zoonderkins/blahdns/assets/6301735/9dacf7e1-d578-4de6-ac24-f5655004f09d">

DoT on Swiss server is working correctly, as well as DnsCrypt
<img width="1006" alt="Screenshot 2024-01-23 at 01 59 23" src="https://github.com/zoonderkins/blahdns/assets/6301735/82532787-0467-4e13-9c68-1ab647104c7c">

**Comment by zoonderkins** [comment]
Hi @LucioAmely  
From what I tested on my machine, Swiss server DoT, DNSCrypt both working normally.

Here is the DNSCrypt lookup
```
 dnslookup example.org sdns://AQMAAAAAAAAAETQ1LjkxLjkyLjEyMTo4NDQzIIhCiTxjWpKpvR2RBDSGoByOMQTzH8DQVVHmdgxroO45GzIuZG5zY3J5cHQtY2VydC5ibGFoZG5zLmNvbQ
dnslookup 1.10.0
Server: sdns://AQMAAAAAAAAAETQ1LjkxLjkyLjEyMTo4NDQzIIhCiTxjWpKpvR2RBDSGoByOMQTzH8DQVVHmdgxroO45GzIuZG5zY3J5cHQtY2VydC5ibGFoZG5zLmNvbQ

dnslookup result (elapsed 615.782458ms):
;; opcode: QUERY, status: NOERROR, id: 18129
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version 0; flags:; udp: 5632

;; QUESTION SECTION:
;example.org.	IN	 A

;; ANSWER SECTION:
example.org.	47361	IN	A	93.184.216.34
```

Here is the DoT lookup 
```
kdig example.org @dot-ch.blahdns.com +tls +tls-hostname=dot-ch.blahdns.com
;; TLS session (TLS1.3)-(ECDHE-X25519)-(RSA-PSS-RSAE-SHA256)-(AES-128-GCM)
;; ->>HEADER<<- opcode: QUERY; status: NOERROR; id: 4131
;; Flags: qr rd ra ad; QUERY: 1; ANSWER: 1; AUTHORITY: 0; ADDITIONAL: 1

;; EDNS PSEUDOSECTION:
;; Version: 0; flags: ; UDP size: 4096 B; ext-rcode: NOERROR

;; QUESTION SECTION:
;; example.org.        		IN	A

;; ANSWER SECTION:
example.org.        	47248	IN	A	93.184.216.34

;; Received 56 B
;; Time 2024-01-23 02:00:46 CST
;; From 45.91.92.121@853(TLS) in 896.0 ms
```

**Comment by LucioAmely** [comment]
Issue looks like this I assume. I am not sure if anybody else is having problems as well. I've been using your DNS service for years without any problems and grateful to you for that.

https://github.com/DNSCrypt/dnscrypt-resolvers/issues/62

**Comment by daemonserj** [comment]
I've checked dot-ch with  dnslookup  and getdns_query on various hosts.
Now it looks fine.

**Comment by LucioAmely** [comment]
It's sadly still the same for me. @zoonderkins can you please tell us what was the problem in the servers and what actions taken to solve them, maybe I can figure out what got changed and find the cause of my connectivity problems.

**Comment by zoonderkins** [comment]
1. TLS certificate renew and TLS key length alter -> 2048
2. Bump HaProxy to 2.9
3. re-compile dns-over-https to latest version Golang 1.21

I think that's it, the rest still the same ~

**Comment by LucioAmely** [comment]
> 1. TLS certificate renew and TLS key length alter -> 2048

Ahh so SPKI fingerprint got changed, most likely that's why my DoT setup was not working.

About DnsCrypt, what can be the problem?:

`Incorrect signature for provider name: [2.dnscrypt-cert.blahdns.com.]`

**Comment by zoonderkins** [comment]
Please try with this dnscrypt 

```
Provider public key: 8842893c635a92a9bd1d91043486a01c8e3104f31fc0d05551e6760c6ba0ee39
DNS Stamp: sdns://AQMAAAAAAAAAETQ1LjkxLjkyLjEyMTo4NDQzIIhCiTxjWpKpvR2RBDSGoByOMQTzH8DQVVHmdgxroO45GzIuZG5zY3J5cHQtY2VydC5ibGFoZG5zLmNvbQ

DNS Stamp: sdns://AQMAAAAAAAAAF1syYTBlOmRjMDo2OjIzOjoyXTo4NDQzIIhCiTxjWpKpvR2RBDSGoByOMQTzH8DQVVHmdgxroO45GzIuZG5zY3J5cHQtY2VydC5ibGFoZG5zLmNvbQ

Provider public key: 8842893c635a92a9bd1d91043486a01c8e3104f31fc0d05551e6760c6ba0ee39
Provider name: 2.dnscrypt-cert.blahdns.com
```

**Comment by LucioAmely** [comment]
> Please try with this dnscrypt
> 
> ```
> Provider public key: 8842893c635a92a9bd1d91043486a01c8e3104f31fc0d05551e6760c6ba0ee39
> DNS Stamp: sdns://AQMAAAAAAAAAETQ1LjkxLjkyLjEyMTo4NDQzIIhCiTxjWpKpvR2RBDSGoByOMQTzH8DQVVHmdgxroO45GzIuZG5zY3J5cHQtY2VydC5ibGFoZG5zLmNvbQ
> 
> DNS Stamp: sdns://AQMAAAAAAAAAF1syYTBlOmRjMDo2OjIzOjoyXTo4NDQzIIhCiTxjWpKpvR2RBDSGoByOMQTzH8DQVVHmdgxroO45GzIuZG5zY3J5cHQtY2VydC5ibGFoZG5zLmNvbQ
> 
> Provider public key: 8842893c635a92a9bd1d91043486a01c8e3104f31fc0d05551e6760c6ba0ee39
> Provider name: 2.dnscrypt-cert.blahdns.com
> ```

IPv4 one works perfectly, could not test IPv6 since all IPv6 connections are blocked in my network. Thank you for solving this issue.

**Comment by LucioAmely** [comment]
CH DoT stopped responding around 30 minutes ago.

**Comment by zoonderkins** [comment]
Sorry for the late reply.
Can you connect through port 853 instead of 443 ?
I plan migrate to standard DoT i  the future.
